AWSTemplateFormatVersion: 2010-09-09
Description: Bots at Brown

Parameters:
    BucketName:
        Description: S3 Bucket
        Type: String

    SourceFolder:
        Description: folder in S3 Bucket where source files are located (lambda)
        Type: String
        Default: "src"

Resources:

    BrownBotFunctionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                -   Effect: Allow
                    Principal:
                        Service:
                        - lambda.amazonaws.com
                    Action:
                    - sts:AssumeRole
            Policies:
                -   PolicyName: Allow-logs
                    PolicyDocument:
                        Version: '2012-10-17'
                        Statement:
                        -   Effect: Allow
                            Action:
                            - 'logs:CreateLogGroup'
                            - 'logs:CreateLogStream'
                            - 'logs:PutLogEvents'
                            Resource: arn:aws:logs:*:*:*
                -   PolicyName: BucketGetPutObject
                    PolicyDocument:
                        Version: '2012-10-17'
                        Statement:
                        -   Effect: Allow
                            Action:
                            - 's3:GetObject'
                            - 's3:PutObject'
                            Resource:
                                Fn::Join: ["", ["arn:aws:s3:::", Ref: "BucketName", "/*"]]


    BrownBotFunction:
        Type: AWS::Lambda::Function
        Properties:
            Runtime: python3.7
            Description: Function to run a bot.
            Handler: src/lambda_function.lambda_handler
            Role:
                Fn::GetAtt: [ "BrownBotFunctionRole", "Arn" ]
            Environment:
                Variables:
                    PYTHONPATH: "/var/task/src:/opt/python"
                    PATH: "/opt/bin:/opt/bin/lib"
                    BUCKET:
                        Ref: BucketName
            Timeout: 60
            MemorySize: 2048
            Code:
                S3Bucket:
                    Ref: BucketName
                S3Key:
                    Fn::Sub: '${SourceFolder}/BrownBotFunction.zip'
            Layers:
                - Ref: SeleniumChromiumLayer

    SeleniumChromiumLayer:
        Type: AWS::Lambda::LayerVersion
        Properties:
            CompatibleRuntimes:
                - python3.7
                - python3.6
            Content:
                S3Bucket:
                    Ref: BucketName
                S3Key:
                    Fn::Sub: '${SourceFolder}/SeleniumChromiumLayer.zip'
            Description: Selenium and Chromium Layer for Python3.6

